### ISSUE TITLE
results.flat is not a function

### ISSUE THREAD

**Issue by freearhey** [detroitenglish/iptv-checker-module#2]
Maybe you know why this error could appear?

<img width="484" alt="Captura de pantalla 2020-04-17 a las 17 48 47" src="https://user-images.githubusercontent.com/7253922/79581915-c03e8900-80d3-11ea-98ee-67ff26d67d6f.png">

The `results` seems to contain an ordinary array but the test constantly produces 'results.flat is not a function'.

https://github.com/detroitenglish/iptv-checker-module/blob/b310b4df4b52e2197b872175217ab16e6a2df96b/src/index.js#L78

**Comment by detroitenglish** [comment]
> Maybe you know why this error could appear?

By forgetting that native `Array.flat()` support didn't land until Node 12 😐

Sorry about that - fixed in [v1.0.1](https://www.npmjs.com/package/iptv-checker-module/v/1.0.1)!

**Comment by freearhey** [comment]
I didn't know that. Thank you for enlightening! 

Well, then I'll just update the Node.🤨
