### ISSUE TITLE
[Feature] Add support custom User-Agent and Referer for each link

### ISSUE THREAD

**Issue by freearhey** [detroitenglish/iptv-checker-module#5]
In m3u-playlists it is possible for any link to specify additional tags `#EXTVLCOPT:http-referrer` and `#EXTVLCOPT:http-user-agent`, like so:

```xml
#EXTINF:-1 tvg-id="cnn.us" tvg-name="CNN" tvg-language="English" tvg-country="US" tvg-url="http://195.154.221.171/epg/guide.xml.gz" tvg-logo="http://example.com/logo.png" group-title="News",CNN (US)
#EXTVLCOPT:http-referrer=http://example.com/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5)
http://example.com/stream.m3u8
```

`iptv-playlist-parser` already knows how to parse these tags and if there are any, it saves their value in the `http` property:

```
...
    { 
      name: 'CNN (US)',
      tvg: {
        id: 'cnn.us',
        name: 'CNN',
        language: 'English',
        country: 'US',
        url: 'http://195.154.221.171/epg/guide.xml.gz',
        logo: 'http://example.com/logo.png'
      },
      group: {
        title: 'News'
      },
      http: {
        referrer: 'http://example.com/',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5)'
      },
      url: 'http://example.com/stream.m3u8',
      raw: '#EXTINF:-1 tvg-id="cnn.us" tvg-name="CNN" tvg-language="English" tvg-country="US" tvg-url="http://195.154.221.171/epg/guide.xml.gz" tvg-logo="http://example.com/logo.png" group-title="News",CNN (US)\n#EXTVLCOPT:http-referrer=http://example.com/\n#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5)\nhttp://example.com/stream.m3u8'
    }
...
```

That is, in order to add their support to the module, we only need to pass these values to `ffprobe` command:

```sh
ffprobe -headers "Referer: http://example.com/" -user_agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5)" "path/to/playlist.m3u"
```

I wanted to do this myself, but unfortunately I couldn't figure out the current version of the code, so I really hope that you will have time to implement it.

**Comment by detroitenglish** [comment]
This is definitely doable, but I don't think it should be default behavior.

That means adding another config option like `useItemHttpHeaders` set to `false` by default.

Think that's the right way forward?

**Comment by freearhey** [comment]
Why do you think support for these parameters should not be enabled by default?

**Comment by detroitenglish** [comment]
Just hesitant to change default behaviors, I guess...

Now thinking about it more, default behavior should indeed follow the spec as closely as possible. 

So let's default to `true` but still keep the option to disable the behavior.

Time for a major version bump! 😎

**Comment by freearhey** [comment]
Thank you!

**Comment by Mattheo1985** [comment]
Thanks!

**Comment by detroitenglish** [comment]
@Mattheo1985 you're welcome, random dude!
